## Train a simple convnet on the Fashion MNIST dataset

In this, we will see how to deal with image data and train a convnet for image classification task.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import keras

import warnings
warnings.filterwarnings('ignore')
from keras.models import Sequential
from keras.optimizers import SGD
from keras import regularizers
from keras import optimizers

import matplotlib.pyplot as plt
%matplotlib inline
from keras.layers import Reshape, Dense, Flatten, Dropout,MaxPooling2D, BatchNormalization

C:\Users\rames\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
import tensorflow as tf
tf.set_random_seed(42)

### Load the  `fashion_mnist`  dataset

** Use keras.datasets to load the dataset **

In [4]:
from keras.datasets import fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

### Find no.of samples are there in training and test datasets

In [5]:
print("x_train shape:", x_train.shape, "\ny_train shape:", y_train.shape)

x_train shape: (60000, 28, 28) 
y_train shape: (60000,)


In [6]:
print("x_train shape:", x_test.shape, "\ny_train shape:", y_test.shape)

x_train shape: (10000, 28, 28) 
y_train shape: (10000,)


### Find dimensions of an image in the dataset

In [7]:
print("Dimension of train images",x_train.shape[1:3])
print("Dimension of test images",x_test.shape[1:3])

Dimension of train images (28, 28)
Dimension of test images (28, 28)


### Convert train and test labels to one hot vectors

** check `keras.utils.to_categorical()` **

In [8]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [9]:
print(y_train.shape)
print('First 5 examples now are: ', y_train[0:5])

(60000, 10)
First 5 examples now are:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Normalize both the train and test image data from 0-255 to 0-1

In [10]:
x_train = x_train / 255.0
x_test = x_test / 255.0

In [11]:
x_train.shape

(60000, 28, 28)

In [12]:
print(x_train[0:5])

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


### Reshape the data from 28x28 to 28x28x1 to match input dimensions in Conv2D layer in keras

In [13]:
model = Sequential()
model.add(Reshape((784,),input_shape=(28,28,)))

### Import the necessary layers from keras to build the model

In [14]:
model.add(Dense(units=100,activation="relu"))
model.add(Dense(units=10,activation="softmax"))
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [15]:
model_history = model.fit(x_train, y_train, 
          validation_data=(x_test, y_test), 
          epochs=5,
          batch_size=100)

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 2s 38us/step - loss: 1.0085 - acc: 0.6933 - val_loss: 0.7196 - val_acc: 0.7579
Epoch 2/5
60000/60000 [==============================] - 2s 27us/step - loss: 0.6394 - acc: 0.7902 - val_loss: 0.6112 - val_acc: 0.7928
Epoch 3/5
60000/60000 [==============================] - 2s 28us/step - loss: 0.5657 - acc: 0.8116 - val_loss: 0.5653 - val_acc: 0.8073
Epoch 4/5
60000/60000 [==============================] - 2s 37us/step - loss: 0.5269 - acc: 0.8226 - val_loss: 0.5365 - val_acc: 0.8170
Epoch 5/5
60000/60000 [==============================] - 2s 39us/step - loss: 0.5023 - acc: 0.8288 - val_loss: 0.5210 - val_acc: 0.8201


In [16]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_1 (Reshape)          (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               78500     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
Total params: 79,510
Trainable params: 79,510
Non-trainable params: 0
_________________________________________________________________


In [17]:
accuracy = model.evaluate(x=x_test,y=y_test,batch_size=10)
print("Accuracy: ", accuracy[1])

10000/10000 [==============================] - 1s 75us/step
Accuracy:  0.8200999965965747


In [18]:
# lets try using BatchNormaalization

In [19]:
model = Sequential()

model.add(Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(BatchNormalization())

model.add(Dense(200, activation='sigmoid', name='Layer_1'))

model.add(Dense(100, activation='sigmoid', name='Layer_2'))

model.add(Dense(100, activation='relu', name='Layer_3'))

#Output layer
model.add(keras.layers.Dense(10, activation='softmax', name='Output'))

In [20]:
#Create optimizer with non-default learning rate
sgd_optimizer = optimizers.SGD(lr=0.03)

#Compile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [21]:
model.fit(x_train,y_train,          
          validation_data=(x_test,y_test),
          epochs=10,
          batch_size=50)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 7s 117us/step - loss: 1.1073 - acc: 0.6460 - val_loss: 0.6364 - val_acc: 0.7651
Epoch 2/10
60000/60000 [==============================] - 7s 115us/step - loss: 0.5803 - acc: 0.7878 - val_loss: 0.5335 - val_acc: 0.8067
Epoch 3/10
60000/60000 [==============================] - 6s 105us/step - loss: 0.4988 - acc: 0.8192 - val_loss: 0.4800 - val_acc: 0.8274
Epoch 4/10
60000/60000 [==============================] - 6s 103us/step - loss: 0.4586 - acc: 0.8348 - val_loss: 0.4565 - val_acc: 0.8339
Epoch 5/10
60000/60000 [==============================] - 6s 103us/step - loss: 0.4326 - acc: 0.8434 - val_loss: 0.4294 - val_acc: 0.8428
Epoch 6/10
60000/60000 [==============================] - 6s 103us/step - loss: 0.4116 - acc: 0.8530 - val_loss: 0.4227 - val_acc: 0.8462
Epoch 7/10
60000/60000 [==============================] - 6s 104us/step - loss: 0.3970 - acc: 0.8575 - val_loss: 0.4125 - 

In [22]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_2 (Reshape)          (None, 784)               0         
_________________________________________________________________
batch_normalization_1 (Batch (None, 784)               3136      
_________________________________________________________________
Layer_1 (Dense)              (None, 200)               157000    
_________________________________________________________________
Layer_2 (Dense)              (None, 100)               20100     
_________________________________________________________________
Layer_3 (Dense)              (None, 100)               10100     
_________________________________________________________________
Output (Dense)               (None, 10)                1010      
Total params: 191,346
Trainable params: 189,778
Non-trainable params: 1,568
_________________________________________________________________


In [23]:
accuracy = model.evaluate(x=x_test,y=y_test,batch_size=10)
print("Accuracy: ", accuracy[1])

10000/10000 [==============================] - 1s 104us/step
Accuracy:  0.8589999940991402


In [24]:
# lets try with Dropouts

In [25]:
model = Sequential()

model.add(Reshape((784,),input_shape=(28,28,)))

#Normalize the data
model.add(BatchNormalization())


#Hidden layers
model.add(Dense(200, activation='relu', name='Layer_1'))
model.add(Dense(100, activation='relu', name='Layer_2'))

#Dropout layer
model.add(Dropout(0.5))

#Hidden layers
model.add(Dense(60, activation='relu', name='Layer_3'))
model.add(Dense(30, activation='relu', name='Layer_4'))

#Dropout layer
model.add(Dropout(0.3))

In [26]:
#Output layer
model.add(keras.layers.Dense(10, activation='softmax', name='Output'))

In [27]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [28]:
#Train the model
model.fit(x_train,y_train,          
          validation_data=(x_test,y_test),
          epochs=10,
          batch_size=10)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 33s 547us/step - loss: 0.8050 - acc: 0.7275 - val_loss: 0.4868 - val_acc: 0.8291
Epoch 2/10
60000/60000 [==============================] - 28s 461us/step - loss: 0.5878 - acc: 0.8044 - val_loss: 0.4472 - val_acc: 0.8450
Epoch 3/10
60000/60000 [==============================] - 26s 436us/step - loss: 0.5258 - acc: 0.8269 - val_loss: 0.4523 - val_acc: 0.8409
Epoch 4/10
60000/60000 [==============================] - 26s 434us/step - loss: 0.4918 - acc: 0.8382 - val_loss: 0.4188 - val_acc: 0.8494
Epoch 5/10
60000/60000 [==============================] - 26s 430us/step - loss: 0.4725 - acc: 0.8433 - val_loss: 0.4027 - val_acc: 0.8573
Epoch 6/10
60000/60000 [==============================] - 26s 436us/step - loss: 0.4523 - acc: 0.8491 - val_loss: 0.4014 - val_acc: 0.8601
Epoch 7/10
60000/60000 [==============================] - 26s 437us/step - loss: 0.4377 - acc: 0.8531 - val_loss: 0.

In [29]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_3 (Reshape)          (None, 784)               0         
_________________________________________________________________
batch_normalization_2 (Batch (None, 784)               3136      
_________________________________________________________________
Layer_1 (Dense)              (None, 200)               157000    
_________________________________________________________________
Layer_2 (Dense)              (None, 100)               20100     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
Layer_3 (Dense)              (None, 60)                6060      
_________________________________________________________________
Layer_4 (Dense)              (None, 30)                1830      
__________

In [30]:
accuracy = model.evaluate(x=x_test,y=y_test,batch_size=10)
print("Accuracy: ", accuracy[1])

10000/10000 [==============================] - 1s 109us/step
Accuracy:  0.8683999938964844


In [31]:
###

model = Sequential()

model.add(Reshape((784,),input_shape=(28,28,)))

model.add(Dense(200, activation='sigmoid', name='Layer_1'))

model.add(Dense(100, activation='sigmoid', name='Layer_2'))

model.add(Dense(100, activation='relu', name='Layer_3'))

#Output layer
model.add(keras.layers.Dense(10, activation='softmax', name='Output'))

In [32]:
sgd_optimizer = SGD(lr=0.001,momentum=.8)
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [33]:
#Train the model
model.fit(x_train,y_train,          
          validation_data=(x_test,y_test),
          epochs=30,
          batch_size=20)

Train on 60000 samples, validate on 10000 samples
Epoch 1/30
60000/60000 [==============================] - 10s 167us/step - loss: 1.9828 - acc: 0.3978 - val_loss: 1.4800 - val_acc: 0.5679
Epoch 2/30
60000/60000 [==============================] - 8s 140us/step - loss: 1.1472 - acc: 0.6392 - val_loss: 0.9359 - val_acc: 0.6870
Epoch 3/30
60000/60000 [==============================] - 9s 143us/step - loss: 0.8222 - acc: 0.7103 - val_loss: 0.7575 - val_acc: 0.7157
Epoch 4/30
60000/60000 [==============================] - 8s 139us/step - loss: 0.6997 - acc: 0.7395 - val_loss: 0.6847 - val_acc: 0.7451
Epoch 5/30
60000/60000 [==============================] - 9s 142us/step - loss: 0.6445 - acc: 0.7564 - val_loss: 0.6412 - val_acc: 0.7604
Epoch 6/30
60000/60000 [==============================] - 8s 142us/step - loss: 0.6110 - acc: 0.7702 - val_loss: 0.6217 - val_acc: 0.7695
Epoch 7/30
60000/60000 [==============================] - 9s 143us/step - loss: 0.5873 - acc: 0.7826 - val_loss: 0.6051 -

In [34]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_4 (Reshape)          (None, 784)               0         
_________________________________________________________________
Layer_1 (Dense)              (None, 200)               157000    
_________________________________________________________________
Layer_2 (Dense)              (None, 100)               20100     
_________________________________________________________________
Layer_3 (Dense)              (None, 100)               10100     
_________________________________________________________________
Output (Dense)               (None, 10)                1010      
Total params: 188,210
Trainable params: 188,210
Non-trainable params: 0
_________________________________________________________________


In [35]:
accuracy = model.evaluate(x=x_test,y=y_test,batch_size=10)
print("Accuracy: ", accuracy[1])

10000/10000 [==============================] - 1s 87us/step
Accuracy:  0.8422999946773052


In [36]:
###
Lambda = 1e3
model = Sequential()

model.add(Reshape((784,),input_shape=(28,28,)))

model.add(Dense(200, activation='sigmoid', name='Layer_1'))

model.add(Dense(100, activation='relu', name='Layer_2'))

model.add(Dense(100, activation='relu', name='Layer_3'))

#Output layer
model.add(Dense(10, activation='softmax', kernel_regularizer=regularizers.l2(Lambda)))

sgd_optimizer = SGD(lr=0.001,momentum=.8)
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [37]:
#Train the model
model.fit(x_train,y_train,          
          validation_data=(x_test,y_test),
          epochs=30,
          batch_size=20)

Train on 60000 samples, validate on 10000 samples
Epoch 1/30
60000/60000 [==============================] - 9s 154us/step - loss: 31.9983 - acc: 0.0983 - val_loss: 2.3049 - val_acc: 0.1000
Epoch 2/30
60000/60000 [==============================] - 10s 175us/step - loss: 2.3045 - acc: 0.0987 - val_loss: 2.3049 - val_acc: 0.1000
Epoch 3/30
60000/60000 [==============================] - 11s 186us/step - loss: 2.3044 - acc: 0.0994 - val_loss: 2.3072 - val_acc: 0.1000
Epoch 4/30
60000/60000 [==============================] - 11s 181us/step - loss: 2.3044 - acc: 0.0963 - val_loss: 2.3048 - val_acc: 0.1000
Epoch 5/30
60000/60000 [==============================] - 10s 171us/step - loss: 2.3045 - acc: 0.0985 - val_loss: 2.3048 - val_acc: 0.1000
Epoch 6/30
60000/60000 [==============================] - 10s 161us/step - loss: 2.3045 - acc: 0.0980 - val_loss: 2.3037 - val_acc: 0.1000
Epoch 7/30
60000/60000 [==============================] - 10s 171us/step - loss: 2.3044 - acc: 0.0983 - val_loss: 2.

In [38]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_5 (Reshape)          (None, 784)               0         
_________________________________________________________________
Layer_1 (Dense)              (None, 200)               157000    
_________________________________________________________________
Layer_2 (Dense)              (None, 100)               20100     
_________________________________________________________________
Layer_3 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1010      
Total params: 188,210
Trainable params: 188,210
Non-trainable params: 0
_________________________________________________________________


In [39]:
accuracy = model.evaluate(x=x_test,y=y_test,batch_size=10)
print("Accuracy: ", accuracy[1])

10000/10000 [==============================] - 1s 107us/step
Accuracy:  0.10000000193715096


In [41]:
### with adam optimizer it is giving best accurancy

### Build a model 

** with 2 Conv layers having `32 3*3 filters` in both convolutions with `relu activations` and `flatten` before passing the feature map into 2 fully connected layers (or Dense Layers) having 128 and 10 neurons with `relu` and `softmax` activations respectively. Now, using `categorical_crossentropy` loss with `adam` optimizer train the model with early stopping `patience=5` and no.of `epochs=10`. **

### Now, to the above model add `max` pooling layer of `filter size 2x2` and `dropout` layer with `p=0.25` after the 2 conv layers and run the model

### Now, to the above model, lets add Data Augmentation 

### Import the ImageDataGenrator from keras and fit the training images

#### Showing 5 versions of the first image in training dataset using image datagenerator.flow()

In [40]:
from matplotlib import pyplot as plt
gen = datagen.flow(x_train[0:1], batch_size=1)
for i in range(1, 6):
    plt.subplot(1,5,i)
    plt.axis("off")
    plt.imshow(gen.next().squeeze(), cmap='gray')
    plt.plot()
plt.show()

NameError: name 'datagen' is not defined

### Run the above model using fit_generator()

###  Report the final train and validation accuracy

## **DATA AUGMENTATION ON CIFAR10 DATASET**

One of the best ways to improve the performance of a Deep Learning model is to add more data to the training set. Aside from gathering more instances from the wild that are representative of the distinction task, we want to develop a set of methods that enhance the data we already have. There are many ways to augment existing datasets and produce more robust models. In the image domain, these are done to utilize the full power of the convolutional neural network, which is able to capture translational invariance. This translational invariance is what makes image recognition such a difficult task in the first place. You want the dataset to be representative of the many different positions, angles, lightings, and miscellaneous distortions that are of interest to the vision task.

### **Import neessary libraries for data augmentation**

### **Load CIFAR10 dataset**

### **Create a data_gen funtion to genererator with image rotation,shifting image horizontally and vertically with random flip horizontally.**

### **Prepare/fit the generator.**

### **Generate 5 images for 1 of the image of CIFAR10 train dataset.**